// Code related to display numbers via single digits on small 5x5 NeoPixel-Matrix

#ifndef _DIGIT_DISPLAY_H_
#define _DIGIT_DISPLAY_H_

#define PPM_BLNK_ 0x00, 0x00, 0x00
#define PPM_COLOR 0x00, 0x00, 0xFF

#define DIGIT_WIDTH 5
#define DIGIT_HEIGHT 5

#define SCROLL_LEFT_MERGE_TO_RIGHT 0
#define SCROLL_BOTTOM_MERGE_TO_TOP 1
#define SCROLL_RIGHT_MERGE_TO_LEFT 2
#define SCROLL_TOP_MERGE_TO_BOTTOM 3

void matrix_fill(long color_GGRRBB);
unsigned char *rotate_buffer90(unsigned char *num);
void digit_to_buf(byte number, byte rot_count);
void merge_buffers(unsigned char *target, int *target_width, int *target_height, byte merge_direction);

const unsigned char  empty[75] =
{
    PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_BLNK_,
    PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_BLNK_,
    PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_BLNK_,
    PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_BLNK_,
    PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_BLNK_,
};
const unsigned char  zero[75] =
{
    PPM_BLNK_, PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_BLNK_,
    PPM_BLNK_, PPM_COLOR, PPM_BLNK_, PPM_BLNK_, PPM_COLOR,
    PPM_BLNK_, PPM_COLOR, PPM_BLNK_, PPM_BLNK_, PPM_COLOR,
    PPM_BLNK_, PPM_COLOR, PPM_BLNK_, PPM_BLNK_, PPM_COLOR,
    PPM_BLNK_, PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_BLNK_,
};
const unsigned char  one[75] =
{
    PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_COLOR, PPM_BLNK_,
    PPM_BLNK_, PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_BLNK_,
    PPM_BLNK_, PPM_COLOR, PPM_BLNK_, PPM_COLOR, PPM_BLNK_,
    PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_COLOR, PPM_BLNK_,
    PPM_BLNK_, PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_COLOR,
};
const unsigned char  two[75] =
{
    PPM_BLNK_, PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_BLNK_,
    PPM_BLNK_, PPM_COLOR, PPM_BLNK_, PPM_BLNK_, PPM_COLOR,
    PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_COLOR, PPM_BLNK_,
    PPM_BLNK_, PPM_BLNK_, PPM_COLOR, PPM_BLNK_, PPM_BLNK_,
    PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_COLOR, PPM_COLOR,
};
const unsigned char  three[75] =
{
    PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_COLOR, PPM_BLNK_,
    PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_COLOR,
    PPM_BLNK_, PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_BLNK_,
    PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_COLOR,
    PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_COLOR, PPM_BLNK_,
};
const unsigned char  four[75] =
{
    PPM_BLNK_, PPM_COLOR, PPM_BLNK_, PPM_BLNK_, PPM_BLNK_,
    PPM_BLNK_, PPM_COLOR, PPM_BLNK_, PPM_COLOR, PPM_BLNK_,
    PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_COLOR, PPM_COLOR,
    PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_COLOR, PPM_BLNK_,
    PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_COLOR, PPM_BLNK_,
};
const unsigned char  five[75] =
{
    PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_COLOR, PPM_COLOR,
    PPM_BLNK_, PPM_COLOR, PPM_BLNK_, PPM_BLNK_, PPM_BLNK_,
    PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_COLOR, PPM_BLNK_,
    PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_COLOR,
    PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_COLOR, PPM_BLNK_,
};
const unsigned char  six[75] =
{
    PPM_BLNK_, PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_COLOR,
    PPM_BLNK_, PPM_COLOR, PPM_BLNK_, PPM_BLNK_, PPM_BLNK_,
    PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_COLOR, PPM_BLNK_,
    PPM_BLNK_, PPM_COLOR, PPM_BLNK_, PPM_BLNK_, PPM_COLOR,
    PPM_BLNK_, PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_BLNK_,
};
const unsigned char  seven[75] =
{
    PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_COLOR, PPM_COLOR,
    PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_COLOR,
    PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_COLOR, PPM_BLNK_,
    PPM_BLNK_, PPM_BLNK_, PPM_COLOR, PPM_BLNK_, PPM_BLNK_,
    PPM_BLNK_, PPM_COLOR, PPM_BLNK_, PPM_BLNK_, PPM_BLNK_,
};
const unsigned char  eight[75] =
{
    PPM_BLNK_, PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_BLNK_,
    PPM_BLNK_, PPM_COLOR, PPM_BLNK_, PPM_BLNK_, PPM_COLOR,
    PPM_BLNK_, PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_BLNK_,
    PPM_BLNK_, PPM_COLOR, PPM_BLNK_, PPM_BLNK_, PPM_COLOR,
    PPM_BLNK_, PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_BLNK_,
};
const unsigned char  nine[75] =
{
    PPM_BLNK_, PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_BLNK_,
    PPM_BLNK_, PPM_COLOR, PPM_BLNK_, PPM_BLNK_, PPM_COLOR,
    PPM_BLNK_, PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_COLOR,
    PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_BLNK_, PPM_COLOR,
    PPM_BLNK_, PPM_COLOR, PPM_COLOR, PPM_COLOR, PPM_BLNK_,
};

#endif // _DIGIT_DISPLAY_H_